// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiU7VVs_9KXsLv1DAdNOdf2Bjep3YDeV4',
    appId: '1:488145274548:web:dfc6c62907d894290ab9e1',
    messagingSenderId: '488145274548',
    projectId: 'teachersguard',
    authDomain: 'teachersguard.firebaseapp.com',
    storageBucket: 'teachersguard.appspot.com',
    measurementId: 'G-D5BM1CRLSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy9IO4cF8VcghOe0GaSPNXh7aPjC78Bn0',
    appId: '1:488145274548:android:560d247d8288d0cb0ab9e1',
    messagingSenderId: '488145274548',
    projectId: 'teachersguard',
    storageBucket: 'teachersguard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9-eQ9_7c9A7FxwDFQIFK-ka4OHKtImM',
    appId: '1:488145274548:ios:9b2c9d0e79110cb30ab9e1',
    messagingSenderId: '488145274548',
    projectId: 'teachersguard',
    storageBucket: 'teachersguard.appspot.com',
    iosBundleId: 'com.example.teachersguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF9-eQ9_7c9A7FxwDFQIFK-ka4OHKtImM',
    appId: '1:488145274548:ios:bf72ad657bdf14390ab9e1',
    messagingSenderId: '488145274548',
    projectId: 'teachersguard',
    storageBucket: 'teachersguard.appspot.com',
    iosBundleId: 'com.example.teachersguard.RunnerTests',
  );
}
